### ISSUE TITLE
Multiple Wall Connectors - metrics mixed into same graph

### ISSUE THREAD

**Issue by R0ltec** [benclapp/tesla_wall_connector_exporter#24]
Is there a way to change the metric name on each additional docker container running the exporter? I added a second Wall connector and immediately, my Grafana duplicated all the same metrics into the existing graphs I created for the first Exporter docker. I noticed that when doing a search for lets say "voltage", only 1 would come up instead of each individual one. This is causing the new metric to overlay into the same graph and doesn't allow renaming of the metric either without it also renaming the original.

**Comment by R0ltec** [comment]
Was able to just edit the command and add the job name. This separated the graphs. For anyone else this means each docker container added needs to have a unique name obviously and this is what is used within Grafana to display what you specifically want.

**Comment by benclapp** [comment]
Hey there! The metric names are hard coded. I only have the one wall connector, and intended this exporter to keep a 1:1 mapping to the wall connector it's gathering metrics for. 

I was expecting for cases where there may be multiple, might've been to use Prometheus relabel rules to add any extra labels that may be useful for identification purposes. For example, something like this to add a `charger_name` label.

```yaml
  - target_label: "charger_name"
    replacement: "the blue one"
```

The `teslawallconnector_info` metric also has some labels you can use with joins in your queries, such as `serial_number`. How things are aggregated and visualised in Grafana will depend on your queries, sounds like you may be aggregating by the `job` label. This is an example query from my dashboard, to show the power, and adds the `serial_number` label to a metric that does not have that label.

```promql
rate(teslawallconnector_session_energy_watt_hours_total[$__rate_interval]) * 3600
* on() group_left(serial_number) 
teslawallconnector_info
```
